name: CICD

on:
  push:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: run tests
        run: mvn test
      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.0.1
      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco.outputs.branches }}"
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-report
          path: target/site/jacoco
  build:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Package
        run: mvn package
  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy-DEV:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: dev
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy DEV"
  deploy-STG:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: stg
    if: github.ref == 'refs/heads/release'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy STG"
  smoke-test:
    runs-on: ubuntu-latest
    needs: [deploy-STG, deploy-DEV]
    environment:
      name: test
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        shell: bash
        run: |
          sh 'src/main/scripts/smoketest.sh'
  deploy-PRD:
    runs-on: ubuntu-latest
    needs: publish
    environment:
      name: prd
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy
        shell: bash
        run: |
          echo "Deploy PRD"
  release:
    runs-on: ubuntu-latest
    needs: deploy-PRD
    environment:
      name: prd
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Release
        shell: bash
        run: |
          echo "Release ${{github.run_number}}"
